#!/usr/bin/python

from os import system
from os.path import expanduser, exists

home = expanduser('~')

warning = False

def check(filename):
    if exists(home + '/' + filename):
        print 'File %s already exists!' % filename
        print 'Moving the current %s to %s_backup' % (filename, filename)
        system('mv ~/%s ~/%s_backup' % (filename, filename))
        warning = True

check('.bash_profile')
system('echo source $HOME/dotfiles/bash/bash_profile.sh > ~/.bash_profile')

# TODO: make a vim-plug install
check('.vimrc')
system('echo source $HOME/dotfiles/vim/vimrc > ~/.vimrc')

check('.tmux.conf')
system('echo source $HOME/dotfiles/.tmux.conf > ~/.tmux.conf')

if warning:
    print '>> You may want to update your dotfiles <<'

system('echo -e "[user]\n  name = William\n  email = pedroschneider@outlook.com" >> .gitconfig')


print 'Done!'
