#!/usr/bin/python

import os

from os.path import expanduser

home = expanduser('~')

warning = False

def check(filename):
    if os.path.exists(home + '/' +filename):
        print 'File %s already exists!' % filename
        print 'Moving the current %s to %s_backup' % (filename, filename)
        os.system('mv ~/%s ~/%s_backup' % (filename, filename))
        warning = True

check('.bash_profile')
os.system('echo source $HOME/dotfiles/bash/bash_profile.sh > ~/.bash_profile')

check('.vimrc')
os.system('echo source $HOME/dotfiles/vim/vimrc > ~/.vimrc')

check('.tmux.conf')
os.system('echo source $HOME/dotfiles/.tmux.conf > ~/.tmux.conf')

if warning:
    print '>> You may want to update your dotfiles <<'

print 'Done!'
